# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from deep_translator import GoogleTranslator


class Ui_EviTranslate(object):
    def setupUi(self, EviTranslate):
        EviTranslate.setObjectName("EviTranslate")
        EviTranslate.resize(712, 440)
        EviTranslate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(EviTranslate)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 370, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.translate)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 150, 311, 211))
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(370, 150, 311, 211))
        self.plainTextEdit_2.setPlainText("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 130, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(310, 70, 41, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 20, 581, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(430, 410, 251, 20))
        self.label_5.setObjectName("label_5")
        EviTranslate.setCentralWidget(self.centralwidget)

        self.retranslateUi(EviTranslate)
        QtCore.QMetaObject.connectSlotsByName(EviTranslate)

    def retranslateUi(self, EviTranslate):
        _translate = QtCore.QCoreApplication.translate
        EviTranslate.setWindowTitle(_translate("EviTranslate", "EviTranslate"))
        self.pushButton.setText(_translate("EviTranslate", "Translate"))
        self.label.setText(_translate("EviTranslate", "Enter the language to be translated to:"))
        self.label_2.setText(_translate("EviTranslate", "Auto Language Detect (Input text)"))
        self.label_3.setText(_translate("EviTranslate", "Translated Text"))
        self.comboBox.setItemText(0, _translate("EviTranslate", "de"))
        self.comboBox.setItemText(1, _translate("EviTranslate", "en"))
        self.comboBox.setItemText(2, _translate("EviTranslate", "bn"))
        self.comboBox.setItemText(3, _translate("EviTranslate", "fr"))
        self.comboBox.setItemText(4, _translate("EviTranslate", "ko"))
        self.comboBox.setItemText(5, _translate("EviTranslate", "ru"))
        self.comboBox.setItemText(6, _translate("EviTranslate", "es"))
        self.comboBox.setItemText(7, _translate("EviTranslate", "it"))
        self.label_4.setText(_translate("EviTranslate", "Translate any language to your preferred language from our list."))
        self.label_5.setText(_translate("EviTranslate", "Designed & Developed by Abdullah, Under the GPL"))
        self.update()
        
    def translate(self):
        self.lang = self.comboBox.currentText()
        self.word = self.plainTextEdit.toPlainText()
        self.translated = GoogleTranslator(source='auto', target=self.lang).translate(self.word)
        self.plainTextEdit_2.setText(self.translated)
        
    def update(self):
        self.label_5.adjustSize()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EviTranslate = QtWidgets.QMainWindow()
    ui = Ui_EviTranslate()
    ui.setupUi(EviTranslate)
    EviTranslate.show()
    sys.exit(app.exec())
